Repository OpenBeta/open-tacos, pull requests merged in 2022-10, with the labels that each got.

#569 Delete tick
  src/components/media/__tests__/UserGallery.tsx
  src/components/users/ImportFromMtnProj.tsx
  src/components/users/PublicProfile.tsx
  src/components/users/TickButton.tsx
  src/components/users/TickCard.tsx
  src/components/users/TickForm.tsx
  src/components/users/TicksModal.tsx
  src/components/users/__tests__/PublicProfile.tsx
  src/js/graphql/fragments.ts
  src/js/types.ts
  src/js/types/User.ts
  src/pages/api/user/metadataClient.ts
  src/pages/api/user/ticks.ts
  src/pages/climbs/[id].tsx
Labels: needs testing, feature

#587 Adjust filter popover text color (fixes #584)
  src/components/ui/FilterPopover.tsx
Labels: HACKTOBERFEST-ACCEPTED

#586 New Country table of content
  src/components/ui/BreadCrumbs.tsx
  src/js/graphql/api.ts
  src/js/graphql/fragments.ts
  src/js/types.ts
  src/pages/a/[[...slug]].tsx
  yarn.lock
Labels: WIP
